apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-6mq5q
    field.cattle.io/ingressState: '{"amVua2lucy9iYXNlL2plbmtpbnMud2ViLy84MDgw":""}'
    field.cattle.io/publicEndpoints: '[{"addresses":["10.40.20.2"],"port":80,"protocol":"HTTP","serviceName":"base:jenkins","ingressName":"base:jenkins","hostname":"jenkins.web","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"field.cattle.io/creatorId":"user-6mq5q","field.cattle.io/ingressState":"{\"amVua2lucy9iYXNlL2plbmtpbnMud2ViLy84MDgw\":\"\"}","field.cattle.io/publicEndpoints":"[{\"addresses\":[\"10.40.20.2\"],\"port\":80,\"protocol\":\"HTTP\",\"serviceName\":\"base:jenkins\",\"ingressName\":\"base:jenkins\",\"hostname\":\"jenkins.web\",\"allNodes\":true}]"},"creationTimestamp":null,"generation":1,"name":"jenkins","namespace":"base","selfLink":"/apis/extensions/v1beta1/namespaces/base/ingresses/jenkins"},"spec":{"rules":[{"host":"jenkins.web","http":{"paths":[{"backend":{"serviceName":"jenkins","servicePort":8080}}]}}]},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  generation: 1
  name: jenkins
  selfLink: /apis/extensions/v1beta1/namespaces/base/ingresses/jenkins
spec:
  rules:
  - host: jenkins.web
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
status:
  loadBalancer: {}
