apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-6mq5q
    field.cattle.io/ipAddresses: '["10.40.20.2"]'
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"field.cattle.io/creatorId":"user-6mq5q","field.cattle.io/ipAddresses":"[\"10.40.20.2\"]","field.cattle.io/targetDnsRecordIds":"null","field.cattle.io/targetWorkloadIds":"null"},"creationTimestamp":null,"name":"rancher","namespace":"web","selfLink":"/api/v1/namespaces/web/services/rancher"},"spec":{"clusterIP":"None","ports":[{"name":"default","port":42,"protocol":"TCP","targetPort":42}],"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  name: rancher
  selfLink: /api/v1/namespaces/web/services/rancher
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
