apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-js6v2
    field.cattle.io/ipAddresses: '["10.40.20.2"]'
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  creationTimestamp: null
  name: reigstry
  selfLink: /api/v1/namespaces/web/services/reigstry
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
