apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-2xdrm
    field.cattle.io/publicEndpoints: '[{"addresses":["10.40.20.2"],"port":80,"protocol":"HTTP","serviceName":"base:jenkins","ingressName":"base:jenkins","hostname":"jenkins.web","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","field.cattle.io/creatorId":"user-2xdrm","field.cattle.io/publicEndpoints":"[{\"addresses\":[\"10.40.20.2\"],\"port\":80,\"protocol\":\"HTTP\",\"serviceName\":\"base:jenkins\",\"ingressName\":\"base:jenkins\",\"hostname\":\"jenkins.web\",\"allNodes\":true}]"},"creationTimestamp":null,"generation":1,"labels":{"workload.user.cattle.io/workloadselector":"deployment-base-jenkins"},"name":"jenkins","namespace":"base","selfLink":"/apis/apps/v1beta2/namespaces/base/deployments/jenkins"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-base-jenkins"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"field.cattle.io/ports":"[[{\"containerPort\":8080,\"dnsName\":\"jenkins\",\"kind\":\"ClusterIP\",\"name\":\"8080tcp80802\",\"protocol\":\"TCP\",\"sourcePort\":8080}]]"},"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"deployment-base-jenkins"}},"spec":{"affinity":{},"containers":[{"args":["/var/jenkins_home/kube/setup_kubectl.sh"],"command":["bash"],"env":[{"name":"DOCKER_PWD","value":"jiaozw"},{"name":"DOCKER_USR","value":"jiaozw"}],"image":"registry.cn-beijing.aliyuncs.com/im_wower/jenkins-in-kubernetes:lts-k8s","imagePullPolicy":"Always","name":"jenkins","ports":[{"containerPort":8080,"name":"8080tcp80802","protocol":"TCP"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/jenkins_home","name":"vol1"},{"mountPath":"/var/run/docker.sock","name":"vol2"},{"mountPath":"/usr/share/maven/conf/settings.xml","name":"vol3"},{"mountPath":"/var/jenkins_home/.m2","name":"vol4"}]}],"dnsPolicy":"ClusterFirstWithHostNet","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/mnt/sda1/rancher/jenkins_k8s_data","type":"DirectoryOrCreate"},"name":"vol1"},{"hostPath":{"path":"/var/run/docker.sock","type":"File"},"name":"vol2"},{"hostPath":{"path":"/mnt/sda1/rancher/jenkins_k8s_data/maven/settings.xml","type":"DirectoryOrCreate"},"name":"vol3"},{"hostPath":{"path":"/mnt/sda1/rancher/jenkins_k8s_data/maven/.m2","type":"DirectoryOrCreate"},"name":"vol4"}]}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-base-jenkins
  name: jenkins
  selfLink: /apis/apps/v1beta2/namespaces/base/deployments/jenkins
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-base-jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"jenkins","kind":"ClusterIP","name":"8080tcp80802","protocol":"TCP","sourcePort":8080}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-base-jenkins
    spec:
      affinity: {}
      containers:
      - args:
        - /var/jenkins_home/kube/setup_kubectl.sh
        command:
        - bash
        env:
        - name: DOCKER_PWD
          value: jiaozw
        - name: DOCKER_USR
          value: jiaozw
        image: registry.cn-beijing.aliyuncs.com/im_wower/jenkins-in-kubernetes:lts-k8s
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
          name: 8080tcp80802
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: vol1
        - mountPath: /var/run/docker.sock
          name: vol2
        - mountPath: /usr/share/maven/conf/settings.xml
          name: vol3
        - mountPath: /var/jenkins_home/.m2
          name: vol4
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/sda1/rancher/jenkins_k8s_data
          type: DirectoryOrCreate
        name: vol1
      - hostPath:
          path: /var/run/docker.sock
          type: File
        name: vol2
      - hostPath:
          path: /mnt/sda1/rancher/jenkins_k8s_data/maven/settings.xml
          type: DirectoryOrCreate
        name: vol3
      - hostPath:
          path: /mnt/sda1/rancher/jenkins_k8s_data/maven/.m2
          type: DirectoryOrCreate
        name: vol4
status: {}
