apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-9rgsm
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"6","field.cattle.io/creatorId":"user-9rgsm"},"creationTimestamp":null,"generation":1,"labels":{"workload.user.cattle.io/workloadselector":"deployment-base-kubectl"},"name":"kubectl","namespace":"base","selfLink":"/apis/apps/v1beta2/namespaces/base/deployments/kubectl"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-base-kubectl"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"deployment-base-kubectl"}},"spec":{"affinity":{},"containers":[{"args":["/opt/kubectl/ubuntu-kubectl-in-docker/setup_kubectl.sh"],"command":["bash"],"image":"registry.cn-beijing.aliyuncs.com/im_wower/ubuntu-kubectl-in-docker","imagePullPolicy":"Always","name":"kubectl","resources":{},"securityContext":{"allowPrivilegeEscalation":false,"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true,"volumeMounts":[{"mountPath":"/opt/kubectl","name":"vol1"},{"mountPath":"/var/run/docker.sock","name":"vol2"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/mnt/sda1/rancher/kubectl_data","type":"DirectoryOrCreate"},"name":"vol1"},{"hostPath":{"path":"/var/run/docker.sock","type":"File"},"name":"vol2"}]}}},"status":{}}'
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-base-kubectl
  name: kubectl
  selfLink: /apis/apps/v1beta2/namespaces/base/deployments/kubectl
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-base-kubectl
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-base-kubectl
    spec:
      affinity: {}
      containers:
      - args:
        - /opt/kubectl/ubuntu-kubectl-in-docker/setup_kubectl.sh
        command:
        - bash
        image: registry.cn-beijing.aliyuncs.com/im_wower/ubuntu-kubectl-in-docker
        imagePullPolicy: Always
        name: kubectl
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/kubectl
          name: vol1
        - mountPath: /var/run/docker.sock
          name: vol2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/sda1/rancher/kubectl_data
          type: DirectoryOrCreate
        name: vol1
      - hostPath:
          path: /var/run/docker.sock
          type: File
        name: vol2
status: {}
