apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-c45zd
    field.cattle.io/publicEndpoints: "null"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","field.cattle.io/creatorId":"user-c45zd","field.cattle.io/publicEndpoints":"[{\"addresses\":[\"10.40.20.2\"],\"port\":80,\"protocol\":\"HTTP\",\"serviceName\":\"base:mongo\",\"ingressName\":\"base:mongo\",\"hostname\":\"mongo.web\",\"allNodes\":true}]"},"creationTimestamp":null,"generation":1,"labels":{"workload.user.cattle.io/workloadselector":"deployment-base-mongo"},"name":"mongo","namespace":"base","selfLink":"/apis/apps/v1beta2/namespaces/base/deployments/mongo"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-base-mongo"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"field.cattle.io/ports":"[[{\"containerPort\":27017,\"dnsName\":\"mongo\",\"kind\":\"ClusterIP\",\"name\":\"27017tcp270172\",\"protocol\":\"TCP\",\"sourcePort\":27017}]]"},"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"deployment-base-mongo"}},"spec":{"affinity":{},"containers":[{"image":"mongo","imagePullPolicy":"Always","name":"mongo","ports":[{"containerPort":27017,"name":"27017tcp270172","protocol":"TCP"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true,"volumeMounts":[{"mountPath":"/data/db","name":"vol1"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/mnt/sda1/rancher/mongo_data","type":"DirectoryOrCreate"},"name":"vol1"}]}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-base-mongo
  name: mongo
  selfLink: /apis/apps/v1beta2/namespaces/base/deployments/mongo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-base-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":27017,"dnsName":"mongo","kind":"ClusterIP","name":"27017tcp270172","protocol":"TCP","sourcePort":27017}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-base-mongo
    spec:
      affinity: {}
      containers:
      - image: mongo
        imagePullPolicy: Always
        name: mongo
        ports:
        - containerPort: 27017
          name: 27017tcp270172
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data/db
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/sda1/rancher/mongo_data
          type: DirectoryOrCreate
        name: vol1
status: {}
